server:
  port: 7800

spring:
  profiles:
    active: @profileActive@
  application:
    name: user-server
  datasource:
    url: jdbc:mysql://localhost:3306/ninja_user?useUnicode=true&characterEncoding=utf-8&useSSL=false&useInformationSchema=true&remarks=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver


eureka:
  client:
    service-url:
      defaultZone: http://localhost:7900/eureka/