
package cn.com.yangshj.monitor.webservice.event;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EventServiceDevImpl", targetNamespace = "http://impl.event.dev.bsm.mocha.com/", wsdlLocation = "http://172.30.251.75/pureportal/webservices/event?wsdl")
public class EventServiceDevImpl
    extends Service
{

    private final static URL EVENTSERVICEDEVIMPL_WSDL_LOCATION;
    private final static WebServiceException EVENTSERVICEDEVIMPL_EXCEPTION;
    private final static QName EVENTSERVICEDEVIMPL_QNAME = new QName("http://impl.event.dev.bsm.mocha.com/", "EventServiceDevImpl");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://172.30.251.75/pureportal/webservices/event?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EVENTSERVICEDEVIMPL_WSDL_LOCATION = url;
        EVENTSERVICEDEVIMPL_EXCEPTION = e;
    }

    public EventServiceDevImpl() {
        super(__getWsdlLocation(), EVENTSERVICEDEVIMPL_QNAME);
    }

    public EventServiceDevImpl(WebServiceFeature... features) {
        super(__getWsdlLocation(), EVENTSERVICEDEVIMPL_QNAME, features);
    }

    public EventServiceDevImpl(URL wsdlLocation) {
        super(wsdlLocation, EVENTSERVICEDEVIMPL_QNAME);
    }

    public EventServiceDevImpl(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EVENTSERVICEDEVIMPL_QNAME, features);
    }

    public EventServiceDevImpl(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EventServiceDevImpl(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EventServiceDevImplPortType
     */
    @WebEndpoint(name = "EventServiceDevImplPort")
    public EventServiceDevImplPortType getEventServiceDevImplPort() {
        return super.getPort(new QName("http://impl.event.dev.bsm.mocha.com/", "EventServiceDevImplPort"), EventServiceDevImplPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EventServiceDevImplPortType
     */
    @WebEndpoint(name = "EventServiceDevImplPort")
    public EventServiceDevImplPortType getEventServiceDevImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.event.dev.bsm.mocha.com/", "EventServiceDevImplPort"), EventServiceDevImplPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EVENTSERVICEDEVIMPL_EXCEPTION!= null) {
            throw EVENTSERVICEDEVIMPL_EXCEPTION;
        }
        return EVENTSERVICEDEVIMPL_WSDL_LOCATION;
    }

}
