
package cn.com.yangshj.monitor.webservice.event;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EventServiceDevImplPortType", targetNamespace = "http://impl.event.dev.bsm.mocha.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EventServiceDevImplPortType {


    /**
     * 
     * @param eventGroupId
     * @param timeMills
     * @param objectName
     * @param moduleId
     * @param token
     * @return
     *     returns cn.com.yangshj.monitor.webservice.event.EventCountObj
     */
    @WebMethod
    @WebResult(targetNamespace = "http://impl.event.dev.bsm.mocha.com/")
    @RequestWrapper(localName = "getActiveEventCountByServerTime", targetNamespace = "http://impl.event.dev.bsm.mocha.com/", className = "cn.com.yangshj.monitor.webservice.event.GetActiveEventCountByServerTime")
    @ResponseWrapper(localName = "getActiveEventCountByServerTimeResponse", targetNamespace = "http://impl.event.dev.bsm.mocha.com/", className = "cn.com.yangshj.monitor.webservice.event.GetActiveEventCountByServerTimeResponse")
    public EventCountObj getActiveEventCountByServerTime(
        @WebParam(name = "token", targetNamespace = "http://impl.event.dev.bsm.mocha.com/")
        String token,
        @WebParam(name = "moduleId", targetNamespace = "http://impl.event.dev.bsm.mocha.com/")
        ArrayOfString moduleId,
        @WebParam(name = "eventGroupId", targetNamespace = "http://impl.event.dev.bsm.mocha.com/")
        ArrayOfString eventGroupId,
        @WebParam(name = "objectName", targetNamespace = "http://impl.event.dev.bsm.mocha.com/")
        String objectName,
        @WebParam(name = "timeMills", targetNamespace = "http://impl.event.dev.bsm.mocha.com/")
        String timeMills);

    /**
     * 
     * @param eventGroupId
     * @param objectName
     * @param startTime
     * @param endTime
     * @param moduleId
     * @param token
     * @return
     *     returns cn.com.yangshj.monitor.webservice.event.EventCountObj
     */
    @WebMethod
    @WebResult(targetNamespace = "http://impl.event.dev.bsm.mocha.com/")
    @RequestWrapper(localName = "getHistoryEventCountByClientTime", targetNamespace = "http://impl.event.dev.bsm.mocha.com/", className = "cn.com.yangshj.monitor.webservice.event.GetHistoryEventCountByClientTime")
    @ResponseWrapper(localName = "getHistoryEventCountByClientTimeResponse", targetNamespace = "http://impl.event.dev.bsm.mocha.com/", className = "cn.com.yangshj.monitor.webservice.event.GetHistoryEventCountByClientTimeResponse")
    public EventCountObj getHistoryEventCountByClientTime(
        @WebParam(name = "token", targetNamespace = "http://impl.event.dev.bsm.mocha.com/")
        String token,
        @WebParam(name = "moduleId", targetNamespace = "http://impl.event.dev.bsm.mocha.com/")
        ArrayOfString moduleId,
        @WebParam(name = "eventGroupId", targetNamespace = "http://impl.event.dev.bsm.mocha.com/")
        ArrayOfString eventGroupId,
        @WebParam(name = "objectName", targetNamespace = "http://impl.event.dev.bsm.mocha.com/")
        String objectName,
        @WebParam(name = "startTime", targetNamespace = "http://impl.event.dev.bsm.mocha.com/")
        String startTime,
        @WebParam(name = "endTime", targetNamespace = "http://impl.event.dev.bsm.mocha.com/")
        String endTime);

    /**
     * 
     * @param eventGroupId
     * @param objectName
     * @param pageSize
     * @param startTime
     * @param endTime
     * @param moduleId
     * @param currentPage
     * @param token
     * @return
     *     returns cn.com.yangshj.monitor.webservice.event.ArrayOfEventListObj
     */
    @WebMethod
    @WebResult(targetNamespace = "http://impl.event.dev.bsm.mocha.com/")
    @RequestWrapper(localName = "getActiveEventListByClientTime", targetNamespace = "http://impl.event.dev.bsm.mocha.com/", className = "cn.com.yangshj.monitor.webservice.event.GetActiveEventListByClientTime")
    @ResponseWrapper(localName = "getActiveEventListByClientTimeResponse", targetNamespace = "http://impl.event.dev.bsm.mocha.com/", className = "cn.com.yangshj.monitor.webservice.event.GetActiveEventListByClientTimeResponse")
    public ArrayOfEventListObj getActiveEventListByClientTime(
        @WebParam(name = "token", targetNamespace = "http://impl.event.dev.bsm.mocha.com/")
        String token,
        @WebParam(name = "moduleId", targetNamespace = "http://impl.event.dev.bsm.mocha.com/")
        ArrayOfString moduleId,
        @WebParam(name = "eventGroupId", targetNamespace = "http://impl.event.dev.bsm.mocha.com/")
        ArrayOfString eventGroupId,
        @WebParam(name = "objectName", targetNamespace = "http://impl.event.dev.bsm.mocha.com/")
        String objectName,
        @WebParam(name = "startTime", targetNamespace = "http://impl.event.dev.bsm.mocha.com/")
        String startTime,
        @WebParam(name = "endTime", targetNamespace = "http://impl.event.dev.bsm.mocha.com/")
        String endTime,
        @WebParam(name = "pageSize", targetNamespace = "http://impl.event.dev.bsm.mocha.com/")
        String pageSize,
        @WebParam(name = "currentPage", targetNamespace = "http://impl.event.dev.bsm.mocha.com/")
        String currentPage);

    /**
     * 
     * @param eventGroupId
     * @param timeMills
     * @param objectName
     * @param pageSize
     * @param moduleId
     * @param currentPage
     * @param token
     * @return
     *     returns cn.com.yangshj.monitor.webservice.event.ArrayOfEventListObj
     */
    @WebMethod
    @WebResult(targetNamespace = "http://impl.event.dev.bsm.mocha.com/")
    @RequestWrapper(localName = "getActiveEventListByServerTime", targetNamespace = "http://impl.event.dev.bsm.mocha.com/", className = "cn.com.yangshj.monitor.webservice.event.GetActiveEventListByServerTime")
    @ResponseWrapper(localName = "getActiveEventListByServerTimeResponse", targetNamespace = "http://impl.event.dev.bsm.mocha.com/", className = "cn.com.yangshj.monitor.webservice.event.GetActiveEventListByServerTimeResponse")
    public ArrayOfEventListObj getActiveEventListByServerTime(
        @WebParam(name = "token", targetNamespace = "http://impl.event.dev.bsm.mocha.com/")
        String token,
        @WebParam(name = "moduleId", targetNamespace = "http://impl.event.dev.bsm.mocha.com/")
        ArrayOfString moduleId,
        @WebParam(name = "eventGroupId", targetNamespace = "http://impl.event.dev.bsm.mocha.com/")
        ArrayOfString eventGroupId,
        @WebParam(name = "objectName", targetNamespace = "http://impl.event.dev.bsm.mocha.com/")
        String objectName,
        @WebParam(name = "pageSize", targetNamespace = "http://impl.event.dev.bsm.mocha.com/")
        String pageSize,
        @WebParam(name = "currentPage", targetNamespace = "http://impl.event.dev.bsm.mocha.com/")
        String currentPage,
        @WebParam(name = "timeMills", targetNamespace = "http://impl.event.dev.bsm.mocha.com/")
        String timeMills);

    /**
     * 
     * @param eventGroupId
     * @param timeMills
     * @param objectName
     * @param pageSize
     * @param moduleId
     * @param currentPage
     * @param token
     * @return
     *     returns cn.com.yangshj.monitor.webservice.event.ArrayOfEventListObj
     */
    @WebMethod
    @WebResult(targetNamespace = "http://impl.event.dev.bsm.mocha.com/")
    @RequestWrapper(localName = "getHistoryEventListByServerTime", targetNamespace = "http://impl.event.dev.bsm.mocha.com/", className = "cn.com.yangshj.monitor.webservice.event.GetHistoryEventListByServerTime")
    @ResponseWrapper(localName = "getHistoryEventListByServerTimeResponse", targetNamespace = "http://impl.event.dev.bsm.mocha.com/", className = "cn.com.yangshj.monitor.webservice.event.GetHistoryEventListByServerTimeResponse")
    public ArrayOfEventListObj getHistoryEventListByServerTime(
        @WebParam(name = "token", targetNamespace = "http://impl.event.dev.bsm.mocha.com/")
        String token,
        @WebParam(name = "moduleId", targetNamespace = "http://impl.event.dev.bsm.mocha.com/")
        ArrayOfString moduleId,
        @WebParam(name = "eventGroupId", targetNamespace = "http://impl.event.dev.bsm.mocha.com/")
        ArrayOfString eventGroupId,
        @WebParam(name = "objectName", targetNamespace = "http://impl.event.dev.bsm.mocha.com/")
        String objectName,
        @WebParam(name = "pageSize", targetNamespace = "http://impl.event.dev.bsm.mocha.com/")
        String pageSize,
        @WebParam(name = "currentPage", targetNamespace = "http://impl.event.dev.bsm.mocha.com/")
        String currentPage,
        @WebParam(name = "timeMills", targetNamespace = "http://impl.event.dev.bsm.mocha.com/")
        String timeMills);

    /**
     * 
     * @param eventGroupId
     * @param objectName
     * @param startTime
     * @param endTime
     * @param moduleId
     * @param token
     * @return
     *     returns cn.com.yangshj.monitor.webservice.event.EventCountObj
     */
    @WebMethod
    @WebResult(targetNamespace = "http://impl.event.dev.bsm.mocha.com/")
    @RequestWrapper(localName = "getActiveEventCountByClientTime", targetNamespace = "http://impl.event.dev.bsm.mocha.com/", className = "cn.com.yangshj.monitor.webservice.event.GetActiveEventCountByClientTime")
    @ResponseWrapper(localName = "getActiveEventCountByClientTimeResponse", targetNamespace = "http://impl.event.dev.bsm.mocha.com/", className = "cn.com.yangshj.monitor.webservice.event.GetActiveEventCountByClientTimeResponse")
    public EventCountObj getActiveEventCountByClientTime(
        @WebParam(name = "token", targetNamespace = "http://impl.event.dev.bsm.mocha.com/")
        String token,
        @WebParam(name = "moduleId", targetNamespace = "http://impl.event.dev.bsm.mocha.com/")
        ArrayOfString moduleId,
        @WebParam(name = "eventGroupId", targetNamespace = "http://impl.event.dev.bsm.mocha.com/")
        ArrayOfString eventGroupId,
        @WebParam(name = "objectName", targetNamespace = "http://impl.event.dev.bsm.mocha.com/")
        String objectName,
        @WebParam(name = "startTime", targetNamespace = "http://impl.event.dev.bsm.mocha.com/")
        String startTime,
        @WebParam(name = "endTime", targetNamespace = "http://impl.event.dev.bsm.mocha.com/")
        String endTime);

    /**
     * 
     * @param platformKey
     * @return
     *     returns cn.com.yangshj.monitor.webservice.event.ArrayOfString
     */
    @WebMethod
    @WebResult(targetNamespace = "http://impl.event.dev.bsm.mocha.com/")
    @RequestWrapper(localName = "queryRules", targetNamespace = "http://impl.event.dev.bsm.mocha.com/", className = "cn.com.yangshj.monitor.webservice.event.QueryRules")
    @ResponseWrapper(localName = "queryRulesResponse", targetNamespace = "http://impl.event.dev.bsm.mocha.com/", className = "cn.com.yangshj.monitor.webservice.event.QueryRulesResponse")
    public ArrayOfString queryRules(
        @WebParam(name = "platformKey", targetNamespace = "http://impl.event.dev.bsm.mocha.com/")
        String platformKey);

    /**
     * 
     * @param eventGroupId
     * @param timeMills
     * @param objectName
     * @param moduleId
     * @param token
     * @return
     *     returns cn.com.yangshj.monitor.webservice.event.EventCountObj
     */
    @WebMethod
    @WebResult(targetNamespace = "http://impl.event.dev.bsm.mocha.com/")
    @RequestWrapper(localName = "getHistoryEventCountByServerTime", targetNamespace = "http://impl.event.dev.bsm.mocha.com/", className = "cn.com.yangshj.monitor.webservice.event.GetHistoryEventCountByServerTime")
    @ResponseWrapper(localName = "getHistoryEventCountByServerTimeResponse", targetNamespace = "http://impl.event.dev.bsm.mocha.com/", className = "cn.com.yangshj.monitor.webservice.event.GetHistoryEventCountByServerTimeResponse")
    public EventCountObj getHistoryEventCountByServerTime(
        @WebParam(name = "token", targetNamespace = "http://impl.event.dev.bsm.mocha.com/")
        String token,
        @WebParam(name = "moduleId", targetNamespace = "http://impl.event.dev.bsm.mocha.com/")
        ArrayOfString moduleId,
        @WebParam(name = "eventGroupId", targetNamespace = "http://impl.event.dev.bsm.mocha.com/")
        ArrayOfString eventGroupId,
        @WebParam(name = "objectName", targetNamespace = "http://impl.event.dev.bsm.mocha.com/")
        String objectName,
        @WebParam(name = "timeMills", targetNamespace = "http://impl.event.dev.bsm.mocha.com/")
        String timeMills);

    /**
     * 
     * @param eventGroupId
     * @param objectName
     * @param pageSize
     * @param startTime
     * @param endTime
     * @param moduleId
     * @param currentPage
     * @param token
     * @return
     *     returns cn.com.yangshj.monitor.webservice.event.ArrayOfEventListObj
     */
    @WebMethod
    @WebResult(targetNamespace = "http://impl.event.dev.bsm.mocha.com/")
    @RequestWrapper(localName = "getHistoryEventListByClientTime", targetNamespace = "http://impl.event.dev.bsm.mocha.com/", className = "cn.com.yangshj.monitor.webservice.event.GetHistoryEventListByClientTime")
    @ResponseWrapper(localName = "getHistoryEventListByClientTimeResponse", targetNamespace = "http://impl.event.dev.bsm.mocha.com/", className = "cn.com.yangshj.monitor.webservice.event.GetHistoryEventListByClientTimeResponse")
    public ArrayOfEventListObj getHistoryEventListByClientTime(
        @WebParam(name = "token", targetNamespace = "http://impl.event.dev.bsm.mocha.com/")
        String token,
        @WebParam(name = "moduleId", targetNamespace = "http://impl.event.dev.bsm.mocha.com/")
        ArrayOfString moduleId,
        @WebParam(name = "eventGroupId", targetNamespace = "http://impl.event.dev.bsm.mocha.com/")
        ArrayOfString eventGroupId,
        @WebParam(name = "objectName", targetNamespace = "http://impl.event.dev.bsm.mocha.com/")
        String objectName,
        @WebParam(name = "startTime", targetNamespace = "http://impl.event.dev.bsm.mocha.com/")
        String startTime,
        @WebParam(name = "endTime", targetNamespace = "http://impl.event.dev.bsm.mocha.com/")
        String endTime,
        @WebParam(name = "pageSize", targetNamespace = "http://impl.event.dev.bsm.mocha.com/")
        String pageSize,
        @WebParam(name = "currentPage", targetNamespace = "http://impl.event.dev.bsm.mocha.com/")
        String currentPage);

    /**
     * 
     * @param event
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "http://impl.event.dev.bsm.mocha.com/")
    @RequestWrapper(localName = "send", targetNamespace = "http://impl.event.dev.bsm.mocha.com/", className = "cn.com.yangshj.monitor.webservice.event.Send")
    @ResponseWrapper(localName = "sendResponse", targetNamespace = "http://impl.event.dev.bsm.mocha.com/", className = "cn.com.yangshj.monitor.webservice.event.SendResponse")
    public String send(
        @WebParam(name = "event", targetNamespace = "http://impl.event.dev.bsm.mocha.com/")
        EventObj event);

}
