
package cn.com.yangshj.monitor.webservice.metrics;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MetricDataServiceDevImplPortType", targetNamespace = "http://impl.metricdata.dev.bsm.mocha.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MetricDataServiceDevImplPortType {


    /**
     * 
     * @return
     *     returns cn.com.yangshj.monitor.webservice.metrics.SummaryFrequency
     */
    @WebMethod
    @WebResult(targetNamespace = "http://impl.metricdata.dev.bsm.mocha.com/")
    @RequestWrapper(localName = "getSummaryFrequency", targetNamespace = "http://impl.metricdata.dev.bsm.mocha.com/", className = "cn.com.yangshj.monitor.webservice.metrics.GetSummaryFrequency")
    @ResponseWrapper(localName = "getSummaryFrequencyResponse", targetNamespace = "http://impl.metricdata.dev.bsm.mocha.com/", className = "cn.com.yangshj.monitor.webservice.metrics.GetSummaryFrequencyResponse")
    public SummaryFrequency getSummaryFrequency();

    /**
     * 
     * @param metricIds
     * @param resourceInsIds
     * @return
     *     returns cn.com.yangshj.monitor.webservice.metrics.ArrayOfSimpleMetricData
     */
    @WebMethod
    @WebResult(targetNamespace = "http://impl.metricdata.dev.bsm.mocha.com/")
    @RequestWrapper(localName = "queryRealTimeMetricDataBatch", targetNamespace = "http://impl.metricdata.dev.bsm.mocha.com/", className = "cn.com.yangshj.monitor.webservice.metrics.QueryRealTimeMetricDataBatch")
    @ResponseWrapper(localName = "queryRealTimeMetricDataBatchResponse", targetNamespace = "http://impl.metricdata.dev.bsm.mocha.com/", className = "cn.com.yangshj.monitor.webservice.metrics.QueryRealTimeMetricDataBatchResponse")
    public ArrayOfSimpleMetricData queryRealTimeMetricDataBatch(
        @WebParam(name = "resourceInsIds", targetNamespace = "http://impl.metricdata.dev.bsm.mocha.com/")
        ArrayOfString resourceInsIds,
        @WebParam(name = "metricIds", targetNamespace = "http://impl.metricdata.dev.bsm.mocha.com/")
        ArrayOfString metricIds);

    /**
     * 
     * @param frequencyId
     * @param metricIds
     * @param endDate
     * @param resourceInsIds
     * @param startDate
     * @return
     *     returns cn.com.yangshj.monitor.webservice.metrics.ArrayOfSummarizedMetricData
     */
    @WebMethod
    @WebResult(targetNamespace = "http://impl.metricdata.dev.bsm.mocha.com/")
    @RequestWrapper(localName = "querySummaryMetricDataBatch", targetNamespace = "http://impl.metricdata.dev.bsm.mocha.com/", className = "cn.com.yangshj.monitor.webservice.metrics.QuerySummaryMetricDataBatch")
    @ResponseWrapper(localName = "querySummaryMetricDataBatchResponse", targetNamespace = "http://impl.metricdata.dev.bsm.mocha.com/", className = "cn.com.yangshj.monitor.webservice.metrics.QuerySummaryMetricDataBatchResponse")
    public ArrayOfSummarizedMetricData querySummaryMetricDataBatch(
        @WebParam(name = "resourceInsIds", targetNamespace = "http://impl.metricdata.dev.bsm.mocha.com/")
        ArrayOfString resourceInsIds,
        @WebParam(name = "metricIds", targetNamespace = "http://impl.metricdata.dev.bsm.mocha.com/")
        ArrayOfString metricIds,
        @WebParam(name = "frequencyId", targetNamespace = "http://impl.metricdata.dev.bsm.mocha.com/")
        String frequencyId,
        @WebParam(name = "startDate", targetNamespace = "http://impl.metricdata.dev.bsm.mocha.com/")
        long startDate,
        @WebParam(name = "endDate", targetNamespace = "http://impl.metricdata.dev.bsm.mocha.com/")
        long endDate);

    /**
     * 
     * @param resourceInsId
     * @param frequencyId
     * @param metricId
     * @param endDate
     * @param startDate
     * @return
     *     returns cn.com.yangshj.monitor.webservice.metrics.ArrayOfSummarizedMetricData
     */
    @WebMethod
    @WebResult(targetNamespace = "http://impl.metricdata.dev.bsm.mocha.com/")
    @RequestWrapper(localName = "querySummaryMetricData", targetNamespace = "http://impl.metricdata.dev.bsm.mocha.com/", className = "cn.com.yangshj.monitor.webservice.metrics.QuerySummaryMetricData")
    @ResponseWrapper(localName = "querySummaryMetricDataResponse", targetNamespace = "http://impl.metricdata.dev.bsm.mocha.com/", className = "cn.com.yangshj.monitor.webservice.metrics.QuerySummaryMetricDataResponse")
    public ArrayOfSummarizedMetricData querySummaryMetricData(
        @WebParam(name = "resourceInsId", targetNamespace = "http://impl.metricdata.dev.bsm.mocha.com/")
        String resourceInsId,
        @WebParam(name = "metricId", targetNamespace = "http://impl.metricdata.dev.bsm.mocha.com/")
        String metricId,
        @WebParam(name = "frequencyId", targetNamespace = "http://impl.metricdata.dev.bsm.mocha.com/")
        String frequencyId,
        @WebParam(name = "startDate", targetNamespace = "http://impl.metricdata.dev.bsm.mocha.com/")
        long startDate,
        @WebParam(name = "endDate", targetNamespace = "http://impl.metricdata.dev.bsm.mocha.com/")
        long endDate);

    /**
     * 
     * @param resourceInsId
     * @param metricId
     * @return
     *     returns cn.com.yangshj.monitor.webservice.metrics.SimpleMetricData
     */
    @WebMethod
    @WebResult(targetNamespace = "http://impl.metricdata.dev.bsm.mocha.com/")
    @RequestWrapper(localName = "queryRealTimeMetricData", targetNamespace = "http://impl.metricdata.dev.bsm.mocha.com/", className = "cn.com.yangshj.monitor.webservice.metrics.QueryRealTimeMetricData")
    @ResponseWrapper(localName = "queryRealTimeMetricDataResponse", targetNamespace = "http://impl.metricdata.dev.bsm.mocha.com/", className = "cn.com.yangshj.monitor.webservice.metrics.QueryRealTimeMetricDataResponse")
    public SimpleMetricData queryRealTimeMetricData(
        @WebParam(name = "resourceInsId", targetNamespace = "http://impl.metricdata.dev.bsm.mocha.com/")
        String resourceInsId,
        @WebParam(name = "metricId", targetNamespace = "http://impl.metricdata.dev.bsm.mocha.com/")
        String metricId);

}
