
package cn.com.yangshj.monitor.webservice.metrics;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MetricDataServiceDevImpl", targetNamespace = "http://impl.metricdata.dev.bsm.mocha.com/", wsdlLocation = "http://172.30.251.75//pureportal/webservices/metric?wsdl")
public class MetricDataServiceDevImpl
    extends Service
{

    private final static URL METRICDATASERVICEDEVIMPL_WSDL_LOCATION;
    private final static WebServiceException METRICDATASERVICEDEVIMPL_EXCEPTION;
    private final static QName METRICDATASERVICEDEVIMPL_QNAME = new QName("http://impl.metricdata.dev.bsm.mocha.com/", "MetricDataServiceDevImpl");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://172.30.251.75//pureportal/webservices/metric?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        METRICDATASERVICEDEVIMPL_WSDL_LOCATION = url;
        METRICDATASERVICEDEVIMPL_EXCEPTION = e;
    }

    public MetricDataServiceDevImpl() {
        super(__getWsdlLocation(), METRICDATASERVICEDEVIMPL_QNAME);
    }

    public MetricDataServiceDevImpl(WebServiceFeature... features) {
        super(__getWsdlLocation(), METRICDATASERVICEDEVIMPL_QNAME, features);
    }

    public MetricDataServiceDevImpl(URL wsdlLocation) {
        super(wsdlLocation, METRICDATASERVICEDEVIMPL_QNAME);
    }

    public MetricDataServiceDevImpl(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, METRICDATASERVICEDEVIMPL_QNAME, features);
    }

    public MetricDataServiceDevImpl(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MetricDataServiceDevImpl(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MetricDataServiceDevImplPortType
     */
    @WebEndpoint(name = "MetricDataServiceDevImplPort")
    public MetricDataServiceDevImplPortType getMetricDataServiceDevImplPort() {
        return super.getPort(new QName("http://impl.metricdata.dev.bsm.mocha.com/", "MetricDataServiceDevImplPort"), MetricDataServiceDevImplPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MetricDataServiceDevImplPortType
     */
    @WebEndpoint(name = "MetricDataServiceDevImplPort")
    public MetricDataServiceDevImplPortType getMetricDataServiceDevImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.metricdata.dev.bsm.mocha.com/", "MetricDataServiceDevImplPort"), MetricDataServiceDevImplPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (METRICDATASERVICEDEVIMPL_EXCEPTION!= null) {
            throw METRICDATASERVICEDEVIMPL_EXCEPTION;
        }
        return METRICDATASERVICEDEVIMPL_WSDL_LOCATION;
    }

}
