server:
  port: 7901

spring:
  profiles:
    active: @profileActive@

  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: oauth-server
          uri: lb://oauth-server
          predicates:
            - Path=/oauth/**
          filters:
            - StripPrefix=1
        - id: monitor-server
          uri: lb://monitor-server
          predicates:
            - Path=/monitor/**
          filters:
            - StripPrefix=1
        - id: workflow-server
          uri: lb://workflow-server
          predicates:
            - Path=/workflow/**
          filters:
            - StripPrefix=1



eureka:
  client:
    service-url:
      defaultZone: http://localhost:7900/eureka/