
package cn.com.yangshj.monitor.webservice.system;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SystemServiceDevImplPortType", targetNamespace = "http://impl.system.dev.bsm.mocha.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SystemServiceDevImplPortType {


    /**
     * 
     * @param emailAddress
     * @param title
     * @param content
     * @param token
     * @return
     *     returns cn.com.yangshj.monitor.webservice.system.SystemSendEmailObj
     */
    @WebMethod
    @WebResult(targetNamespace = "http://impl.system.dev.bsm.mocha.com/")
    @RequestWrapper(localName = "sendEmail", targetNamespace = "http://impl.system.dev.bsm.mocha.com/", className = "cn.com.yangshj.monitor.webservice.system.SendEmail")
    @ResponseWrapper(localName = "sendEmailResponse", targetNamespace = "http://impl.system.dev.bsm.mocha.com/", className = "cn.com.yangshj.monitor.webservice.system.SendEmailResponse")
    public SystemSendEmailObj sendEmail(
        @WebParam(name = "token", targetNamespace = "http://impl.system.dev.bsm.mocha.com/")
        String token,
        @WebParam(name = "title", targetNamespace = "http://impl.system.dev.bsm.mocha.com/")
        String title,
        @WebParam(name = "content", targetNamespace = "http://impl.system.dev.bsm.mocha.com/")
        String content,
        @WebParam(name = "emailAddress", targetNamespace = "http://impl.system.dev.bsm.mocha.com/")
        ArrayOfString emailAddress);

}
