
package cn.com.yangshj.monitor.webservice.system;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SystemServiceDevImpl", targetNamespace = "http://impl.system.dev.bsm.mocha.com/", wsdlLocation = "http://172.30.251.75/pureportal/webservices/system?wsdl")
public class SystemServiceDevImpl
    extends Service
{

    private final static URL SYSTEMSERVICEDEVIMPL_WSDL_LOCATION;
    private final static WebServiceException SYSTEMSERVICEDEVIMPL_EXCEPTION;
    private final static QName SYSTEMSERVICEDEVIMPL_QNAME = new QName("http://impl.system.dev.bsm.mocha.com/", "SystemServiceDevImpl");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://172.30.251.75/pureportal/webservices/system?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SYSTEMSERVICEDEVIMPL_WSDL_LOCATION = url;
        SYSTEMSERVICEDEVIMPL_EXCEPTION = e;
    }

    public SystemServiceDevImpl() {
        super(__getWsdlLocation(), SYSTEMSERVICEDEVIMPL_QNAME);
    }

    public SystemServiceDevImpl(WebServiceFeature... features) {
        super(__getWsdlLocation(), SYSTEMSERVICEDEVIMPL_QNAME, features);
    }

    public SystemServiceDevImpl(URL wsdlLocation) {
        super(wsdlLocation, SYSTEMSERVICEDEVIMPL_QNAME);
    }

    public SystemServiceDevImpl(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SYSTEMSERVICEDEVIMPL_QNAME, features);
    }

    public SystemServiceDevImpl(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SystemServiceDevImpl(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SystemServiceDevImplPortType
     */
    @WebEndpoint(name = "SystemServiceDevImplPort")
    public SystemServiceDevImplPortType getSystemServiceDevImplPort() {
        return super.getPort(new QName("http://impl.system.dev.bsm.mocha.com/", "SystemServiceDevImplPort"), SystemServiceDevImplPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SystemServiceDevImplPortType
     */
    @WebEndpoint(name = "SystemServiceDevImplPort")
    public SystemServiceDevImplPortType getSystemServiceDevImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.system.dev.bsm.mocha.com/", "SystemServiceDevImplPort"), SystemServiceDevImplPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SYSTEMSERVICEDEVIMPL_EXCEPTION!= null) {
            throw SYSTEMSERVICEDEVIMPL_EXCEPTION;
        }
        return SYSTEMSERVICEDEVIMPL_WSDL_LOCATION;
    }

}
