
package com.example.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TsCostCenterPortType", targetNamespace = "http://ts.itf.nc/TsCostCenter")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TsCostCenterPortType {


    /**
     * 
     * @param string
     * @param string1
     * @throws BusinessException_Exception
     */
    @WebMethod(action = "urn:tsCostCenter")
    @RequestWrapper(localName = "tsCostCenter", targetNamespace = "http://ts.itf.nc/TsCostCenter", className = "com.example.wsdl.TsCostCenter")
    @ResponseWrapper(localName = "tsCostCenterResponse", targetNamespace = "http://ts.itf.nc/TsCostCenter", className = "com.example.wsdl.TsCostCenterResponse")
    public void tsCostCenter(
        @WebParam(name = "string", targetNamespace = "")
        String string,
        @WebParam(name = "string1", targetNamespace = "")
        String string1)
        throws BusinessException_Exception
    ;

}
