
package cn.com.yangshj.monitor.webservice.instance;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ResourceInstanceServiceDevImpl", targetNamespace = "http://impl.instance.dev.bsm.mocha.com/", wsdlLocation = "http://172.30.251.75/pureportal/webservices/instance?wsdl")
public class ResourceInstanceServiceDevImpl
    extends Service
{

    private final static URL RESOURCEINSTANCESERVICEDEVIMPL_WSDL_LOCATION;
    private final static WebServiceException RESOURCEINSTANCESERVICEDEVIMPL_EXCEPTION;
    private final static QName RESOURCEINSTANCESERVICEDEVIMPL_QNAME = new QName("http://impl.instance.dev.bsm.mocha.com/", "ResourceInstanceServiceDevImpl");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://172.30.251.75/pureportal/webservices/instance?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RESOURCEINSTANCESERVICEDEVIMPL_WSDL_LOCATION = url;
        RESOURCEINSTANCESERVICEDEVIMPL_EXCEPTION = e;
    }

    public ResourceInstanceServiceDevImpl() {
        super(__getWsdlLocation(), RESOURCEINSTANCESERVICEDEVIMPL_QNAME);
    }

    public ResourceInstanceServiceDevImpl(WebServiceFeature... features) {
        super(__getWsdlLocation(), RESOURCEINSTANCESERVICEDEVIMPL_QNAME, features);
    }

    public ResourceInstanceServiceDevImpl(URL wsdlLocation) {
        super(wsdlLocation, RESOURCEINSTANCESERVICEDEVIMPL_QNAME);
    }

    public ResourceInstanceServiceDevImpl(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RESOURCEINSTANCESERVICEDEVIMPL_QNAME, features);
    }

    public ResourceInstanceServiceDevImpl(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ResourceInstanceServiceDevImpl(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ResourceInstanceServiceDevImplPortType
     */
    @WebEndpoint(name = "ResourceInstanceServiceDevImplPort")
    public ResourceInstanceServiceDevImplPortType getResourceInstanceServiceDevImplPort() {
        return super.getPort(new QName("http://impl.instance.dev.bsm.mocha.com/", "ResourceInstanceServiceDevImplPort"), ResourceInstanceServiceDevImplPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ResourceInstanceServiceDevImplPortType
     */
    @WebEndpoint(name = "ResourceInstanceServiceDevImplPort")
    public ResourceInstanceServiceDevImplPortType getResourceInstanceServiceDevImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.instance.dev.bsm.mocha.com/", "ResourceInstanceServiceDevImplPort"), ResourceInstanceServiceDevImplPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RESOURCEINSTANCESERVICEDEVIMPL_EXCEPTION!= null) {
            throw RESOURCEINSTANCESERVICEDEVIMPL_EXCEPTION;
        }
        return RESOURCEINSTANCESERVICEDEVIMPL_WSDL_LOCATION;
    }

}
