
package cn.com.yangshj.monitor.webservice.alert;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "NotificationServiceDevImplPortType", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface NotificationServiceDevImplPortType {


    /**
     * 
     * @param eventGroupId
     * @param objectName
     * @param pageSize
     * @param startTime
     * @param endTime
     * @param moduleId
     * @param confirmFlag
     * @param currentPage
     * @param token
     * @return
     *     returns cn.com.yangshj.monitor.webservice.alert.ArrayOfNotificationListExtendObj
     */
    @WebMethod
    @WebResult(targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
    @RequestWrapper(localName = "getNotificationListByClientTimeForApp", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/", className = "cn.com.yangshj.monitor.webservice.alert.GetNotificationListByClientTimeForApp")
    @ResponseWrapper(localName = "getNotificationListByClientTimeForAppResponse", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/", className = "cn.com.yangshj.monitor.webservice.alert.GetNotificationListByClientTimeForAppResponse")
    public ArrayOfNotificationListExtendObj getNotificationListByClientTimeForApp(
        @WebParam(name = "token", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
        String token,
        @WebParam(name = "moduleId", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
        ArrayOfString moduleId,
        @WebParam(name = "eventGroupId", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
        ArrayOfString eventGroupId,
        @WebParam(name = "objectName", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
        String objectName,
        @WebParam(name = "confirmFlag", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
        String confirmFlag,
        @WebParam(name = "startTime", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
        String startTime,
        @WebParam(name = "endTime", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
        String endTime,
        @WebParam(name = "pageSize", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
        String pageSize,
        @WebParam(name = "currentPage", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
        String currentPage);

    /**
     * 
     * @param flag
     * @param notificationId
     * @param token
     * @return
     *     returns cn.com.yangshj.monitor.webservice.alert.NotificationOperationObj
     */
    @WebMethod
    @WebResult(targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
    @RequestWrapper(localName = "modifyNotification", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/", className = "cn.com.yangshj.monitor.webservice.alert.ModifyNotification")
    @ResponseWrapper(localName = "modifyNotificationResponse", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/", className = "cn.com.yangshj.monitor.webservice.alert.ModifyNotificationResponse")
    public NotificationOperationObj modifyNotification(
        @WebParam(name = "token", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
        String token,
        @WebParam(name = "notificationId", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
        ArrayOfString notificationId,
        @WebParam(name = "flag", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
        String flag);

    /**
     * 
     * @param eventDataId
     * @param instanceId
     * @param token
     * @return
     *     returns cn.com.yangshj.monitor.webservice.alert.NotificationDetailObj
     */
    @WebMethod
    @WebResult(targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
    @RequestWrapper(localName = "getNotificationDetail", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/", className = "cn.com.yangshj.monitor.webservice.alert.GetNotificationDetail")
    @ResponseWrapper(localName = "getNotificationDetailResponse", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/", className = "cn.com.yangshj.monitor.webservice.alert.GetNotificationDetailResponse")
    public NotificationDetailObj getNotificationDetail(
        @WebParam(name = "token", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
        String token,
        @WebParam(name = "eventDataId", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
        String eventDataId,
        @WebParam(name = "instanceId", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
        String instanceId);

    /**
     * 
     * @param eventGroupId
     * @param objectName
     * @param pageSize
     * @param startTime
     * @param endTime
     * @param moduleId
     * @param confirmFlag
     * @param currentPage
     * @param token
     * @return
     *     returns cn.com.yangshj.monitor.webservice.alert.ArrayOfNotificationListExtendObj
     */
    @WebMethod
    @WebResult(targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
    @RequestWrapper(localName = "getNotificationListByModifyClientTimeForApp", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/", className = "cn.com.yangshj.monitor.webservice.alert.GetNotificationListByModifyClientTimeForApp")
    @ResponseWrapper(localName = "getNotificationListByModifyClientTimeForAppResponse", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/", className = "cn.com.yangshj.monitor.webservice.alert.GetNotificationListByModifyClientTimeForAppResponse")
    public ArrayOfNotificationListExtendObj getNotificationListByModifyClientTimeForApp(
        @WebParam(name = "token", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
        String token,
        @WebParam(name = "moduleId", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
        ArrayOfString moduleId,
        @WebParam(name = "eventGroupId", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
        ArrayOfString eventGroupId,
        @WebParam(name = "objectName", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
        String objectName,
        @WebParam(name = "confirmFlag", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
        String confirmFlag,
        @WebParam(name = "startTime", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
        String startTime,
        @WebParam(name = "endTime", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
        String endTime,
        @WebParam(name = "pageSize", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
        String pageSize,
        @WebParam(name = "currentPage", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
        String currentPage);

    /**
     * 
     * @param eventGroupId
     * @param timeMills
     * @param objectName
     * @param moduleId
     * @param confirmFlag
     * @param token
     * @return
     *     returns cn.com.yangshj.monitor.webservice.alert.NotificationMulCountObj
     */
    @WebMethod
    @WebResult(targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
    @RequestWrapper(localName = "getNotificationCountBySeverityIds", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/", className = "cn.com.yangshj.monitor.webservice.alert.GetNotificationCountBySeverityIds")
    @ResponseWrapper(localName = "getNotificationCountBySeverityIdsResponse", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/", className = "cn.com.yangshj.monitor.webservice.alert.GetNotificationCountBySeverityIdsResponse")
    public NotificationMulCountObj getNotificationCountBySeverityIds(
        @WebParam(name = "token", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
        String token,
        @WebParam(name = "moduleId", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
        ArrayOfString moduleId,
        @WebParam(name = "eventGroupId", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
        ArrayOfString eventGroupId,
        @WebParam(name = "objectName", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
        String objectName,
        @WebParam(name = "confirmFlag", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
        String confirmFlag,
        @WebParam(name = "timeMills", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
        String timeMills);

    /**
     * 
     * @param eventGroupId
     * @param timeMills
     * @param objectName
     * @param pageSize
     * @param moduleId
     * @param confirmFlag
     * @param currentPage
     * @param token
     * @return
     *     returns cn.com.yangshj.monitor.webservice.alert.ArrayOfNotificationListObj
     */
    @WebMethod
    @WebResult(targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
    @RequestWrapper(localName = "getNotificationListByServerTime", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/", className = "cn.com.yangshj.monitor.webservice.alert.GetNotificationListByServerTime")
    @ResponseWrapper(localName = "getNotificationListByServerTimeResponse", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/", className = "cn.com.yangshj.monitor.webservice.alert.GetNotificationListByServerTimeResponse")
    public ArrayOfNotificationListObj getNotificationListByServerTime(
        @WebParam(name = "token", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
        String token,
        @WebParam(name = "moduleId", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
        ArrayOfString moduleId,
        @WebParam(name = "eventGroupId", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
        ArrayOfString eventGroupId,
        @WebParam(name = "objectName", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
        String objectName,
        @WebParam(name = "confirmFlag", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
        String confirmFlag,
        @WebParam(name = "pageSize", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
        String pageSize,
        @WebParam(name = "currentPage", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
        String currentPage,
        @WebParam(name = "timeMills", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
        String timeMills);

    /**
     * 
     * @param eventGroupId
     * @param timeMills
     * @param resourceTypeId
     * @param objectName
     * @param moduleId
     * @param confirmFlag
     * @param token
     * @return
     *     returns cn.com.yangshj.monitor.webservice.alert.NotificationCountObj
     */
    @WebMethod
    @WebResult(targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
    @RequestWrapper(localName = "getNotificationCountByResourceType", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/", className = "cn.com.yangshj.monitor.webservice.alert.GetNotificationCountByResourceType")
    @ResponseWrapper(localName = "getNotificationCountByResourceTypeResponse", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/", className = "cn.com.yangshj.monitor.webservice.alert.GetNotificationCountByResourceTypeResponse")
    public NotificationCountObj getNotificationCountByResourceType(
        @WebParam(name = "token", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
        String token,
        @WebParam(name = "moduleId", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
        ArrayOfString moduleId,
        @WebParam(name = "eventGroupId", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
        ArrayOfString eventGroupId,
        @WebParam(name = "resourceTypeId", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
        ArrayOfString resourceTypeId,
        @WebParam(name = "confirmFlag", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
        String confirmFlag,
        @WebParam(name = "objectName", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
        String objectName,
        @WebParam(name = "timeMills", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
        String timeMills);

    /**
     * 
     * @param instId
     * @param actionId
     * @param token
     * @return
     *     returns cn.com.yangshj.monitor.webservice.alert.CommonObj
     */
    @WebMethod
    @WebResult(targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
    @RequestWrapper(localName = "getExecuteScript", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/", className = "cn.com.yangshj.monitor.webservice.alert.GetExecuteScript")
    @ResponseWrapper(localName = "getExecuteScriptResponse", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/", className = "cn.com.yangshj.monitor.webservice.alert.GetExecuteScriptResponse")
    public CommonObj getExecuteScript(
        @WebParam(name = "token", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
        String token,
        @WebParam(name = "instId", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
        String instId,
        @WebParam(name = "actionId", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
        String actionId);

    /**
     * 
     * @param eventGroupId
     * @param objectName
     * @param pageSize
     * @param startTime
     * @param endTime
     * @param moduleId
     * @param confirmFlag
     * @param currentPage
     * @param token
     * @return
     *     returns cn.com.yangshj.monitor.webservice.alert.ArrayOfNotificationListObj
     */
    @WebMethod
    @WebResult(targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
    @RequestWrapper(localName = "getNotificationListByModifyClientTime", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/", className = "cn.com.yangshj.monitor.webservice.alert.GetNotificationListByModifyClientTime")
    @ResponseWrapper(localName = "getNotificationListByModifyClientTimeResponse", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/", className = "cn.com.yangshj.monitor.webservice.alert.GetNotificationListByModifyClientTimeResponse")
    public ArrayOfNotificationListObj getNotificationListByModifyClientTime(
        @WebParam(name = "token", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
        String token,
        @WebParam(name = "moduleId", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
        ArrayOfString moduleId,
        @WebParam(name = "eventGroupId", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
        ArrayOfString eventGroupId,
        @WebParam(name = "objectName", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
        String objectName,
        @WebParam(name = "confirmFlag", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
        String confirmFlag,
        @WebParam(name = "startTime", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
        String startTime,
        @WebParam(name = "endTime", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
        String endTime,
        @WebParam(name = "pageSize", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
        String pageSize,
        @WebParam(name = "currentPage", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
        String currentPage);

    /**
     * 
     * @param eventGroupId
     * @param timeMills
     * @param objectName
     * @param moduleId
     * @param confirmFlag
     * @param token
     * @return
     *     returns cn.com.yangshj.monitor.webservice.alert.NotificationCountObj
     */
    @WebMethod
    @WebResult(targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
    @RequestWrapper(localName = "getNotificationCountByServerTime", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/", className = "cn.com.yangshj.monitor.webservice.alert.GetNotificationCountByServerTime")
    @ResponseWrapper(localName = "getNotificationCountByServerTimeResponse", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/", className = "cn.com.yangshj.monitor.webservice.alert.GetNotificationCountByServerTimeResponse")
    public NotificationCountObj getNotificationCountByServerTime(
        @WebParam(name = "token", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
        String token,
        @WebParam(name = "moduleId", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
        ArrayOfString moduleId,
        @WebParam(name = "eventGroupId", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
        ArrayOfString eventGroupId,
        @WebParam(name = "objectName", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
        String objectName,
        @WebParam(name = "confirmFlag", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
        String confirmFlag,
        @WebParam(name = "timeMills", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
        String timeMills);

    /**
     * 
     * @param eventGroupId
     * @param objectName
     * @param pageSize
     * @param startTime
     * @param endTime
     * @param moduleId
     * @param confirmFlag
     * @param currentPage
     * @param token
     * @return
     *     returns cn.com.yangshj.monitor.webservice.alert.ArrayOfNotificationListObj
     */
    @WebMethod
    @WebResult(targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
    @RequestWrapper(localName = "getNotificationListByClientTime", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/", className = "cn.com.yangshj.monitor.webservice.alert.GetNotificationListByClientTime")
    @ResponseWrapper(localName = "getNotificationListByClientTimeResponse", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/", className = "cn.com.yangshj.monitor.webservice.alert.GetNotificationListByClientTimeResponse")
    public ArrayOfNotificationListObj getNotificationListByClientTime(
        @WebParam(name = "token", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
        String token,
        @WebParam(name = "moduleId", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
        ArrayOfString moduleId,
        @WebParam(name = "eventGroupId", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
        ArrayOfString eventGroupId,
        @WebParam(name = "objectName", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
        String objectName,
        @WebParam(name = "confirmFlag", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
        String confirmFlag,
        @WebParam(name = "startTime", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
        String startTime,
        @WebParam(name = "endTime", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
        String endTime,
        @WebParam(name = "pageSize", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
        String pageSize,
        @WebParam(name = "currentPage", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
        String currentPage);

    /**
     * 
     * @param eventGroupId
     * @param timeMills
     * @param objectName
     * @param moduleId
     * @param token
     * @return
     *     returns cn.com.yangshj.monitor.webservice.alert.ArrayOfNotificationIsConfirmCount
     */
    @WebMethod
    @WebResult(targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
    @RequestWrapper(localName = "getNotificationCountByIsConfirm", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/", className = "cn.com.yangshj.monitor.webservice.alert.GetNotificationCountByIsConfirm")
    @ResponseWrapper(localName = "getNotificationCountByIsConfirmResponse", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/", className = "cn.com.yangshj.monitor.webservice.alert.GetNotificationCountByIsConfirmResponse")
    public ArrayOfNotificationIsConfirmCount getNotificationCountByIsConfirm(
        @WebParam(name = "token", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
        String token,
        @WebParam(name = "moduleId", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
        ArrayOfString moduleId,
        @WebParam(name = "eventGroupId", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
        ArrayOfString eventGroupId,
        @WebParam(name = "objectName", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
        String objectName,
        @WebParam(name = "timeMills", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
        ArrayOfString timeMills);

    /**
     * 
     * @param eventGroupId
     * @param objectName
     * @param startTime
     * @param endTime
     * @param moduleId
     * @param confirmFlag
     * @param token
     * @return
     *     returns cn.com.yangshj.monitor.webservice.alert.NotificationCountObj
     */
    @WebMethod
    @WebResult(targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
    @RequestWrapper(localName = "getNotificationCountByClientTime", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/", className = "cn.com.yangshj.monitor.webservice.alert.GetNotificationCountByClientTime")
    @ResponseWrapper(localName = "getNotificationCountByClientTimeResponse", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/", className = "cn.com.yangshj.monitor.webservice.alert.GetNotificationCountByClientTimeResponse")
    public NotificationCountObj getNotificationCountByClientTime(
        @WebParam(name = "token", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
        String token,
        @WebParam(name = "moduleId", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
        ArrayOfString moduleId,
        @WebParam(name = "eventGroupId", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
        ArrayOfString eventGroupId,
        @WebParam(name = "objectName", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
        String objectName,
        @WebParam(name = "confirmFlag", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
        String confirmFlag,
        @WebParam(name = "startTime", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
        String startTime,
        @WebParam(name = "endTime", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
        String endTime);

    /**
     * 
     * @param eventGroupId
     * @param timeMills
     * @param objectName
     * @param pageSize
     * @param eventSeverityId
     * @param moduleId
     * @param confirmFlag
     * @param currentPage
     * @param token
     * @return
     *     returns cn.com.yangshj.monitor.webservice.alert.ArrayOfNotificationListExtendObj
     */
    @WebMethod
    @WebResult(targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
    @RequestWrapper(localName = "getNotificationListByServerTimeForApp", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/", className = "cn.com.yangshj.monitor.webservice.alert.GetNotificationListByServerTimeForApp")
    @ResponseWrapper(localName = "getNotificationListByServerTimeForAppResponse", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/", className = "cn.com.yangshj.monitor.webservice.alert.GetNotificationListByServerTimeForAppResponse")
    public ArrayOfNotificationListExtendObj getNotificationListByServerTimeForApp(
        @WebParam(name = "token", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
        String token,
        @WebParam(name = "moduleId", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
        ArrayOfString moduleId,
        @WebParam(name = "eventGroupId", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
        ArrayOfString eventGroupId,
        @WebParam(name = "eventSeverityId", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
        ArrayOfString eventSeverityId,
        @WebParam(name = "objectName", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
        String objectName,
        @WebParam(name = "confirmFlag", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
        String confirmFlag,
        @WebParam(name = "pageSize", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
        String pageSize,
        @WebParam(name = "currentPage", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
        String currentPage,
        @WebParam(name = "timeMills", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/")
        String timeMills);

}
