
package cn.com.yangshj.monitor.webservice.alert;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "NotificationServiceDevImpl", targetNamespace = "http://impl.notification.dev.bsm.mocha.com/", wsdlLocation = "http://172.30.251.75/pureportal/webservices/notification?wsdl")
public class NotificationServiceDevImpl
    extends Service
{

    private final static URL NOTIFICATIONSERVICEDEVIMPL_WSDL_LOCATION;
    private final static WebServiceException NOTIFICATIONSERVICEDEVIMPL_EXCEPTION;
    private final static QName NOTIFICATIONSERVICEDEVIMPL_QNAME = new QName("http://impl.notification.dev.bsm.mocha.com/", "NotificationServiceDevImpl");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://172.30.251.75/pureportal/webservices/notification?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        NOTIFICATIONSERVICEDEVIMPL_WSDL_LOCATION = url;
        NOTIFICATIONSERVICEDEVIMPL_EXCEPTION = e;
    }

    public NotificationServiceDevImpl() {
        super(__getWsdlLocation(), NOTIFICATIONSERVICEDEVIMPL_QNAME);
    }

    public NotificationServiceDevImpl(WebServiceFeature... features) {
        super(__getWsdlLocation(), NOTIFICATIONSERVICEDEVIMPL_QNAME, features);
    }

    public NotificationServiceDevImpl(URL wsdlLocation) {
        super(wsdlLocation, NOTIFICATIONSERVICEDEVIMPL_QNAME);
    }

    public NotificationServiceDevImpl(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, NOTIFICATIONSERVICEDEVIMPL_QNAME, features);
    }

    public NotificationServiceDevImpl(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NotificationServiceDevImpl(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns NotificationServiceDevImplPortType
     */
    @WebEndpoint(name = "NotificationServiceDevImplPort")
    public NotificationServiceDevImplPortType getNotificationServiceDevImplPort() {
        return super.getPort(new QName("http://impl.notification.dev.bsm.mocha.com/", "NotificationServiceDevImplPort"), NotificationServiceDevImplPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NotificationServiceDevImplPortType
     */
    @WebEndpoint(name = "NotificationServiceDevImplPort")
    public NotificationServiceDevImplPortType getNotificationServiceDevImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.notification.dev.bsm.mocha.com/", "NotificationServiceDevImplPort"), NotificationServiceDevImplPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (NOTIFICATIONSERVICEDEVIMPL_EXCEPTION!= null) {
            throw NOTIFICATIONSERVICEDEVIMPL_EXCEPTION;
        }
        return NOTIFICATIONSERVICEDEVIMPL_WSDL_LOCATION;
    }

}
