server:
  port: 8100

spring:
  profiles:
    active: @profileActive@

  application:
    name: monitor-server


eureka:
  client:
    service-url:
      defaultZone: http://localhost:7900/eureka/

# a方法
management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    tags:
      application: ${spring.application.name}

# b方法，测试不生效
#endpoints:
#  prometheus:
#    sensitive: false