server:
  port: 8100

spring:
#  profiles:
#    active: @profileActive@
  application:
    name: monitor-server
  jackson:
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://localhost:3306/ninja_monitor?useUnicode=true&characterEncoding=utf-8&useSSL=false&useInformationSchema=true&remarks=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver


eureka:
  client:
    service-url:
      defaultZone: http://localhost:7900/eureka/

## a方法
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#  metrics:
#    tags:
#      application: ${spring.application.name}

# b方法，测试不生效
#endpoints:
#  prometheus:
#    sensitive: false

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.com.yangshj.monitor.test
