server:
  port: 8300

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7900/eureka/

spring:
#  profiles:
#    active: @profileActive@
  application:
    name: oauth-server
  jackson:
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_ninja_oauth?useUnicode=true&characterEncoding=utf-8&useSSL=false&useInformationSchema=true&remarks=true&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher
#    static-path-pattern: /**
  redis:
    host: localhost
    port: 6379
    database: 5
    password: