
package cn.com.yangshj.monitor.webservice.user;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UserServiceDevImplPortType", targetNamespace = "http://impl.user.dev.bsm.mocha.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserServiceDevImplPortType {


    /**
     * 
     * @param userObj
     */
    @WebMethod
    @RequestWrapper(localName = "addUser", targetNamespace = "http://impl.user.dev.bsm.mocha.com/", className = "cn.com.yangshj.monitor.webservice.user.AddUser")
    @ResponseWrapper(localName = "addUserResponse", targetNamespace = "http://impl.user.dev.bsm.mocha.com/", className = "cn.com.yangshj.monitor.webservice.user.AddUserResponse")
    public void addUser(
        @WebParam(name = "userObj", targetNamespace = "http://impl.user.dev.bsm.mocha.com/")
        ArrayOfUserObj userObj);

    /**
     * 
     * @param userId
     */
    @WebMethod
    @RequestWrapper(localName = "deleteUser", targetNamespace = "http://impl.user.dev.bsm.mocha.com/", className = "cn.com.yangshj.monitor.webservice.user.DeleteUser")
    @ResponseWrapper(localName = "deleteUserResponse", targetNamespace = "http://impl.user.dev.bsm.mocha.com/", className = "cn.com.yangshj.monitor.webservice.user.DeleteUserResponse")
    public void deleteUser(
        @WebParam(name = "userId", targetNamespace = "http://impl.user.dev.bsm.mocha.com/")
        ArrayOfString userId);

    /**
     * 
     * @param token
     * @return
     *     returns cn.com.yangshj.monitor.webservice.user.LoginResultObj
     */
    @WebMethod
    @WebResult(targetNamespace = "http://impl.user.dev.bsm.mocha.com/")
    @RequestWrapper(localName = "verifyToken", targetNamespace = "http://impl.user.dev.bsm.mocha.com/", className = "cn.com.yangshj.monitor.webservice.user.VerifyToken")
    @ResponseWrapper(localName = "verifyTokenResponse", targetNamespace = "http://impl.user.dev.bsm.mocha.com/", className = "cn.com.yangshj.monitor.webservice.user.VerifyTokenResponse")
    public LoginResultObj verifyToken(
        @WebParam(name = "token", targetNamespace = "http://impl.user.dev.bsm.mocha.com/")
        String token);

    /**
     * 
     * @param token
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "http://impl.user.dev.bsm.mocha.com/")
    @RequestWrapper(localName = "loginOut", targetNamespace = "http://impl.user.dev.bsm.mocha.com/", className = "cn.com.yangshj.monitor.webservice.user.LoginOut")
    @ResponseWrapper(localName = "loginOutResponse", targetNamespace = "http://impl.user.dev.bsm.mocha.com/", className = "cn.com.yangshj.monitor.webservice.user.LoginOutResponse")
    public String loginOut(
        @WebParam(name = "token", targetNamespace = "http://impl.user.dev.bsm.mocha.com/")
        String token);

    /**
     * 
     * @param password
     * @param phoneNumber
     * @param appType
     * @param loginStr
     * @param imei
     * @return
     *     returns cn.com.yangshj.monitor.webservice.user.LoginResultObj
     */
    @WebMethod
    @WebResult(targetNamespace = "http://impl.user.dev.bsm.mocha.com/")
    @RequestWrapper(localName = "verifyUserByMobile", targetNamespace = "http://impl.user.dev.bsm.mocha.com/", className = "cn.com.yangshj.monitor.webservice.user.VerifyUserByMobile")
    @ResponseWrapper(localName = "verifyUserByMobileResponse", targetNamespace = "http://impl.user.dev.bsm.mocha.com/", className = "cn.com.yangshj.monitor.webservice.user.VerifyUserByMobileResponse")
    public LoginResultObj verifyUserByMobile(
        @WebParam(name = "appType", targetNamespace = "http://impl.user.dev.bsm.mocha.com/")
        String appType,
        @WebParam(name = "loginStr", targetNamespace = "http://impl.user.dev.bsm.mocha.com/")
        String loginStr,
        @WebParam(name = "password", targetNamespace = "http://impl.user.dev.bsm.mocha.com/")
        String password,
        @WebParam(name = "imei", targetNamespace = "http://impl.user.dev.bsm.mocha.com/")
        String imei,
        @WebParam(name = "phoneNumber", targetNamespace = "http://impl.user.dev.bsm.mocha.com/")
        String phoneNumber);

    /**
     * 
     * @param token
     * @return
     *     returns cn.com.yangshj.monitor.webservice.user.String2AnyTypeMap
     */
    @WebMethod
    @WebResult(targetNamespace = "http://impl.user.dev.bsm.mocha.com/")
    @RequestWrapper(localName = "getUserPage", targetNamespace = "http://impl.user.dev.bsm.mocha.com/", className = "cn.com.yangshj.monitor.webservice.user.GetUserPage")
    @ResponseWrapper(localName = "getUserPageResponse", targetNamespace = "http://impl.user.dev.bsm.mocha.com/", className = "cn.com.yangshj.monitor.webservice.user.GetUserPageResponse")
    public String2AnyTypeMap getUserPage(
        @WebParam(name = "token", targetNamespace = "http://impl.user.dev.bsm.mocha.com/")
        String token);

    /**
     * 
     * @param token
     * @return
     *     returns cn.com.yangshj.monitor.webservice.user.String2StringMap
     */
    @WebMethod
    @WebResult(targetNamespace = "http://impl.user.dev.bsm.mocha.com/")
    @RequestWrapper(localName = "getItomConfig", targetNamespace = "http://impl.user.dev.bsm.mocha.com/", className = "cn.com.yangshj.monitor.webservice.user.GetItomConfig")
    @ResponseWrapper(localName = "getItomConfigResponse", targetNamespace = "http://impl.user.dev.bsm.mocha.com/", className = "cn.com.yangshj.monitor.webservice.user.GetItomConfigResponse")
    public String2StringMap getItomConfig(
        @WebParam(name = "token", targetNamespace = "http://impl.user.dev.bsm.mocha.com/")
        String token);

    /**
     * 
     * @param password
     * @param appType
     * @param loginStr
     * @return
     *     returns cn.com.yangshj.monitor.webservice.user.LoginResultObj
     */
    @WebMethod
    @WebResult(targetNamespace = "http://impl.user.dev.bsm.mocha.com/")
    @RequestWrapper(localName = "verifyUser", targetNamespace = "http://impl.user.dev.bsm.mocha.com/", className = "cn.com.yangshj.monitor.webservice.user.VerifyUser")
    @ResponseWrapper(localName = "verifyUserResponse", targetNamespace = "http://impl.user.dev.bsm.mocha.com/", className = "cn.com.yangshj.monitor.webservice.user.VerifyUserResponse")
    public LoginResultObj verifyUser(
        @WebParam(name = "appType", targetNamespace = "http://impl.user.dev.bsm.mocha.com/")
        String appType,
        @WebParam(name = "loginStr", targetNamespace = "http://impl.user.dev.bsm.mocha.com/")
        String loginStr,
        @WebParam(name = "password", targetNamespace = "http://impl.user.dev.bsm.mocha.com/")
        String password);

    /**
     * 
     * @param arg0
     * @return
     *     returns cn.com.yangshj.monitor.webservice.user.ArrayOfWorkGroupObj
     */
    @WebMethod
    @WebResult(targetNamespace = "http://impl.user.dev.bsm.mocha.com/")
    @RequestWrapper(localName = "getWorkGroupByLoginName", targetNamespace = "http://impl.user.dev.bsm.mocha.com/", className = "cn.com.yangshj.monitor.webservice.user.GetWorkGroupByLoginName")
    @ResponseWrapper(localName = "getWorkGroupByLoginNameResponse", targetNamespace = "http://impl.user.dev.bsm.mocha.com/", className = "cn.com.yangshj.monitor.webservice.user.GetWorkGroupByLoginNameResponse")
    public ArrayOfWorkGroupObj getWorkGroupByLoginName(
        @WebParam(name = "arg0", targetNamespace = "http://impl.user.dev.bsm.mocha.com/")
        String arg0);

    /**
     * 
     * @param password
     * @param appType
     * @param loginStr
     * @return
     *     returns cn.com.yangshj.monitor.webservice.user.LoginResultObj
     */
    @WebMethod
    @WebResult(targetNamespace = "http://impl.user.dev.bsm.mocha.com/")
    @RequestWrapper(localName = "verifyUserByRSA", targetNamespace = "http://impl.user.dev.bsm.mocha.com/", className = "cn.com.yangshj.monitor.webservice.user.VerifyUserByRSA")
    @ResponseWrapper(localName = "verifyUserByRSAResponse", targetNamespace = "http://impl.user.dev.bsm.mocha.com/", className = "cn.com.yangshj.monitor.webservice.user.VerifyUserByRSAResponse")
    public LoginResultObj verifyUserByRSA(
        @WebParam(name = "appType", targetNamespace = "http://impl.user.dev.bsm.mocha.com/")
        String appType,
        @WebParam(name = "loginStr", targetNamespace = "http://impl.user.dev.bsm.mocha.com/")
        String loginStr,
        @WebParam(name = "password", targetNamespace = "http://impl.user.dev.bsm.mocha.com/")
        String password);

    /**
     * 
     * @param userObj
     */
    @WebMethod
    @RequestWrapper(localName = "updateUser", targetNamespace = "http://impl.user.dev.bsm.mocha.com/", className = "cn.com.yangshj.monitor.webservice.user.UpdateUser")
    @ResponseWrapper(localName = "updateUserResponse", targetNamespace = "http://impl.user.dev.bsm.mocha.com/", className = "cn.com.yangshj.monitor.webservice.user.UpdateUserResponse")
    public void updateUser(
        @WebParam(name = "userObj", targetNamespace = "http://impl.user.dev.bsm.mocha.com/")
        ArrayOfUserObj userObj);

}
