
package cn.com.yangshj.monitor.webservice.user;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "UserServiceDevImpl", targetNamespace = "http://impl.user.dev.bsm.mocha.com/", wsdlLocation = "http://172.30.251.75/pureportal/webservices/user?wsdl")
public class UserServiceDevImpl
    extends Service
{

    private final static URL USERSERVICEDEVIMPL_WSDL_LOCATION;
    private final static WebServiceException USERSERVICEDEVIMPL_EXCEPTION;
    private final static QName USERSERVICEDEVIMPL_QNAME = new QName("http://impl.user.dev.bsm.mocha.com/", "UserServiceDevImpl");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://172.30.251.75/pureportal/webservices/user?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        USERSERVICEDEVIMPL_WSDL_LOCATION = url;
        USERSERVICEDEVIMPL_EXCEPTION = e;
    }

    public UserServiceDevImpl() {
        super(__getWsdlLocation(), USERSERVICEDEVIMPL_QNAME);
    }

    public UserServiceDevImpl(WebServiceFeature... features) {
        super(__getWsdlLocation(), USERSERVICEDEVIMPL_QNAME, features);
    }

    public UserServiceDevImpl(URL wsdlLocation) {
        super(wsdlLocation, USERSERVICEDEVIMPL_QNAME);
    }

    public UserServiceDevImpl(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, USERSERVICEDEVIMPL_QNAME, features);
    }

    public UserServiceDevImpl(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UserServiceDevImpl(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UserServiceDevImplPortType
     */
    @WebEndpoint(name = "UserServiceDevImplPort")
    public UserServiceDevImplPortType getUserServiceDevImplPort() {
        return super.getPort(new QName("http://impl.user.dev.bsm.mocha.com/", "UserServiceDevImplPort"), UserServiceDevImplPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UserServiceDevImplPortType
     */
    @WebEndpoint(name = "UserServiceDevImplPort")
    public UserServiceDevImplPortType getUserServiceDevImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.user.dev.bsm.mocha.com/", "UserServiceDevImplPort"), UserServiceDevImplPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (USERSERVICEDEVIMPL_EXCEPTION!= null) {
            throw USERSERVICEDEVIMPL_EXCEPTION;
        }
        return USERSERVICEDEVIMPL_WSDL_LOCATION;
    }

}
