server:
  port: 8300

spring:
#  profiles:
#    active: @profileActive@
  application:
    name: rbac-service
  jackson:
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://localhost:3306/liquibase_demo?useUnicode=true&characterEncoding=utf-8&useSSL=false&useInformationSchema=true&remarks=true&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7900/eureka/

