
package cn.com.yangshj.monitor.webservice.busi;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BizsmServiceDevImpl", targetNamespace = "http://impl.bizsm.dev.bsm.mocha.com/", wsdlLocation = "http://172.30.251.75/pureportal/webservices/bizsm?wsdl")
public class BizsmServiceDevImpl
    extends Service
{

    private final static URL BIZSMSERVICEDEVIMPL_WSDL_LOCATION;
    private final static WebServiceException BIZSMSERVICEDEVIMPL_EXCEPTION;
    private final static QName BIZSMSERVICEDEVIMPL_QNAME = new QName("http://impl.bizsm.dev.bsm.mocha.com/", "BizsmServiceDevImpl");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://172.30.251.75/pureportal/webservices/bizsm?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BIZSMSERVICEDEVIMPL_WSDL_LOCATION = url;
        BIZSMSERVICEDEVIMPL_EXCEPTION = e;
    }

    public BizsmServiceDevImpl() {
        super(__getWsdlLocation(), BIZSMSERVICEDEVIMPL_QNAME);
    }

    public BizsmServiceDevImpl(WebServiceFeature... features) {
        super(__getWsdlLocation(), BIZSMSERVICEDEVIMPL_QNAME, features);
    }

    public BizsmServiceDevImpl(URL wsdlLocation) {
        super(wsdlLocation, BIZSMSERVICEDEVIMPL_QNAME);
    }

    public BizsmServiceDevImpl(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BIZSMSERVICEDEVIMPL_QNAME, features);
    }

    public BizsmServiceDevImpl(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BizsmServiceDevImpl(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BizsmServiceDevImplPortType
     */
    @WebEndpoint(name = "BizsmServiceDevImplPort")
    public BizsmServiceDevImplPortType getBizsmServiceDevImplPort() {
        return super.getPort(new QName("http://impl.bizsm.dev.bsm.mocha.com/", "BizsmServiceDevImplPort"), BizsmServiceDevImplPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BizsmServiceDevImplPortType
     */
    @WebEndpoint(name = "BizsmServiceDevImplPort")
    public BizsmServiceDevImplPortType getBizsmServiceDevImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.bizsm.dev.bsm.mocha.com/", "BizsmServiceDevImplPort"), BizsmServiceDevImplPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BIZSMSERVICEDEVIMPL_EXCEPTION!= null) {
            throw BIZSMSERVICEDEVIMPL_EXCEPTION;
        }
        return BIZSMSERVICEDEVIMPL_WSDL_LOCATION;
    }

}
