server:
  port: 7700

spring:
  profiles:
    active: @profileActive@
  application:
    name: base-server
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7900/eureka/